# Generated by Django 5.0.3 on 2024-04-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
