# Generated by Django 5.0.3 on 2024-04-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
