# Generated by Django 5.0.3 on 2024-04-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_otp_auth_url_customuser_otp_base32_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_otp_qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='otp_qr_code'),
        ),
    ]
